"""create model table

Revision ID: 7aacd892c6fc
Revises:
Create Date: 2026-05-26 04:38:14.893978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7aacd892c6fc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "model_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "model_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("training_accuracy", sa.Float(), nullable=False),
        sa.Column("test_accuracy", sa.Float(), nullable=False),
        sa.Column("hyperparameters", sa.JSON(), nullable=True),
        sa.Column(
            "git_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model")
    # ### end Alembic commands ###
